spring:
  datasource:
    url: jdbc:h2:file:/Users/shakti/data/db/demo
    #    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true
    spring.h2.console.settings.web-allow-others: false
